export const Resources = {
  createRecipe: 'Create New Recipe',
  updateRecipe: 'Update Recipe',
  nameLabel: 'Recipe Name',
  namePlaceholder: 'Enter Recipe Name',
  descriptionLabel: 'Recipe Description',
  descriptionPlaceholder: 'Enter a brief description',
  ingredientsLabel: 'Recipe Ingredients',
  ingredientsPlaceholder: 'Enter Recipe Ingredients',
  instructionsLabel: 'Recipe Instructions',
  instructionsPlaceholder: 'Enter detailed instructions',
  tagsLabel: 'Recipe Tags',
  tagsPlaceholder: 'Enter Recipe Tags',
  addTagButton: 'Add Tag',
  removeButton: 'Remove',
  addIngredientButton: 'Add Ingredient',
  updateRecipeButton: 'Update Recipe',
  createRecipeButton: 'Create Recipe',
  cancelButton: 'Cancel',
} as const
